name: medical_kit
description: Application medical kit module
publish_to: none

environment:
  sdk: ^3.3.1
  flutter: ^3.19.3

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core
  core_ui:
    path: ../../core_ui
  domain:
    path: ../../domain
  navigation:
    path: ../../navigation

  toggle_switch: ^2.2.1
  markup_text: ^1.0.4

dev_dependencies:
  lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
