name: core_ui
description: Application core UI module
publish_to: none

environment:
  sdk: ^3.1.3
  flutter: ^3.13.6

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.4

dev_dependencies:
  lints: ^2.0.0
