name: core_ui
description: Application core UI module
publish_to: none

environment:
  sdk: ^3.3.1
  flutter: ^3.19.3

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.4

dev_dependencies:
  lints: ^2.0.0

flutter:
  assets:
    - resources/fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: resources/fonts/Inter-Regular.ttf
          weight: 400
        - asset: resources/fonts/Inter-SemiBold.ttf
          weight: 600
