name: core
description: Application core module
publish_to: none

environment:
  sdk: ^3.3.1
  flutter: ^3.19.3

dependencies:
  flutter:
    sdk: flutter

  domain:
    path: ../domain

  get_it: ^7.6.7
  easy_localization: ^3.0.5
  mask_text_input_formatter: ^2.9.0
  workmanager: ^0.5.2

dev_dependencies:
  lints: ^2.0.0

flutter:
  assets:
    - resources/langs/
