name: core
description: Application core module
publish_to: none

environment:
  sdk: ^3.1.3
  flutter: ^3.13.6

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.6.7

dev_dependencies:
  lints: ^2.0.0
