name: prescriptions
description: Application prescriptions module
publish_to: none

environment:
  sdk: ^3.3.1
  flutter: ^3.19.3

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core
  core_ui:
    path: ../../core_ui
  domain:
    path: ../../domain
  navigation:
    path: ../../navigation
  add_prescription:
    path: ../add_prescription

  calendar_date_picker2: ^0.5.5
  table_calendar: ^3.0.9

dev_dependencies:
  lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
