name: splash
description: Application splash module
publish_to: none

environment:
  sdk: ^3.1.3
  flutter: ^3.13.6

dependencies:
  flutter:
    sdk: flutter

  navigation:
    path: ../../navigation

dev_dependencies:
  lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8