name: "Hello World 2"

on:
  schedule:
    - cron: "6 * * * *" 
    
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
