name: navigation
description: Application navigation module
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.3.1
  flutter: ^3.19.3

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.9.1

  splash:
    path: ../features/splash
  home:
    path: ../features/home
  medical_kit:
    path: ../features/medical_kit

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8